### ISSUE TITLE
LinDA-LMM accommodates categorical exposures only?

### ISSUE THREAD

**Issue by neha-sehgal2** [zhouhj1994/LinDA#12]
Hello, 

Thank you so much for all your hard work and developing the LinDA package such that we can perform DAA for repeated measures.

Question, 
- When using LinDA for repeated measures (lmer4 or linear mixed models), does the main exposure of interest or, any or all of the independent or confounders/effect modifiers have to be categorical variables? 

- Would LinDA's results still be reliable or would there be concerns if the LinDA-lmer4 model has a mix of continuous and categorical variables and our main exposure of interest is a continuous variable. 
I ask so since as per [this link,](https://microbiome.github.io/OMA/differential-abundance.html) it is mentioned that "The output shows effect sizes in terms of log-fold changes and a derived statistic (stat) as well as the corresponding adjusted p-values for differences in abundance of each taxon between the control and treated group."

Thank you for your time and assistance!

**Comment by zhouhj1994** [comment]
The answer to both of your question is No. The variable of interest and confounders can be of any type, categorical or numerical. If the variable of interest is continuous, the statistic and p-value reflect the significance of that variable in relation to abundance.

**Comment by neha-sehgal2** [comment]
Thank you so much for taking the time to clarify! Appreciate it a ton:)
