### ISSUE TITLE
error when more than two fixed effects

### ISSUE THREAD

**Issue by agatagawad** [zhouhj1994/LinDA#2]
Hi,

I have a concern about using variables in the formula.
My formula is ='~Group+Timing+BMI+(1|Subject)', where the first two are factors, and the third one is numeric.
I get this message:
Error in as.data.frame.default(res.cov[which(rownames(res.cov) == x), : cannot coerce class ‘structure("dgeMatrix", package = "Matrix")’ to a data.frame

The same error if the third variable is factor.

If my formula is ~Group+Timing+(1|Subject)' then no problem. 

Many thanks in advance for your help.

Best regards,
Agata

**Comment by zhouhj1994** [comment]
Hi Agata,

Thanks for your interest in our package. That's a bug in the code and has
been fixed. It should work now. Thank you so much for your question!

Please let me know if you have any other questions.

Best,
Huijuan

**Comment by agatagawad** [comment]
Hi  Huijuan,

Thank you very much for fixing the bug! Now everithing works fine.

For the moment I have no questions.

Best regards,
Agata


________________________________
Van: zhouhj1994 ***@***.***>
Verzonden: zondag 15 mei 2022 15:14
Aan: zhouhj1994/LinDA ***@***.***>
CC: Agata Gawad ***@***.***>; Author ***@***.***>
Onderwerp: Re: [zhouhj1994/LinDA] error when more than two fixed effects (Issue #2)


Hi Agata,

Thanks for your interest in our package. That's a bug in the code and has
been fixed. It should work now. Thank you so much for your question!

Please let me know if you have any other questions.

Best,
Huijuan
