### ISSUE TITLE
Any tutorial on how to use the mixed effects models by controling random  effects like age, gender, BMI? 

### ISSUE THREAD

**Issue by biofuture** [zhouhj1994/LinDA#4]
Hello, 

Thanks for the work.  Do you have any tutorial on how to use your package to control the confounding factors like age, gender, BMI while doing this microbial differential abundance/association analysis? 

Thanks.

**Comment by zhouhj1994** [comment]
Hello,

Thanks for the interest. We use similar syntax as for linear programming.
For example, suppose the variable of interest is called treatment, then you
can use* formula = ' ~ **treatment+**age+gender+BMI' *to adjust
confounders. You may look at
*https://cran.r-project.org/web/packages/MicrobiomeStat/MicrobiomeStat.pdf
<https://cran.r-project.org/web/packages/MicrobiomeStat/MicrobiomeStat.pdf>*
for the detailed reference manual of function "linda" in our
"MicrobiomeStat" package. Let me  know if the problem persists.

Thanks,
Huijuan

**Comment by zhouhj1994** [comment]
Hello, Thanks for the interest. We use similar syntax as for the linear
programming. For example, suppose the variable of interest is called
treatment, then you can use* formula = ' ~ **treatment+**age+gender+BMI'
*to adjust confounders. You may look at *
https://cran.r-project.org/web/packages/MicrobiomeStat/MicrobiomeStat.pdf <
https://cran.r-project.org/web/packages/MicrobiomeStat/MicrobiomeStat.pdf>*
for the detailed reference manual of function "linda" in our
"MicrobiomeStat" package. Let me know if the problem persists. Thanks,
Huijuan

**Comment by zhouhj1994** [comment]
Hello, Thanks for the interest. We use similar syntax as for the linear
programming. For example, suppose the variable of interest is called
treatment, then you can use formula = ' ~ treatment+age+gender+BMI' to
adjust confounders. You may look at
https://cran.r-project.org/web/packages/MicrobiomeStat/MicrobiomeStat.pdf <
https://cran.r-project.org/web/packages/MicrobiomeStat/MicrobiomeStat.pdf>
<https://cran.r-project.org/web/packages/MicrobiomeStat/MicrobiomeStat.pdf%3E*>
for the detailed reference manual of function "linda" in our
"MicrobiomeStat" package. Let me know if the problem persists.

Thanks, Huijuan

**Comment by zhouhj1994** [comment]
Hello, Thanks for the interest. We use similar syntax as for the linear
programming. For example, suppose the variable of interest is called
treatment, then you can use formula = ' ~ treatment+age+gender+BMI' to
adjust confounders. You may look at
https://cran.r-project.org/web/packages/MicrobiomeStat/MicrobiomeStat.pdf
for detailed instructions of the function "linda" in our "MicrobiomeStat"
package. Let me know if the problem persists.

Thanks, Huijuan

**Comment by biofuture** [comment]
Thanks, Huijuan, 

do you mean this command in the pdf doc?  

' ~ treatment+age+gender+BMI'. or.  ' ~ **treatment+**age+gender+BMI' *

Let's say, we want to investigate the differential abundant analysis for treatment and geography by adjusting age, gender and BMI.  

I need to use this formula    '~**treatment+geography**+age+gender+BMI', am I correct?    


 Differential abundance analysis pooling both the left and right throat data
Mixed effects model is used

ind <- depth >= 1000
linda.obj <- linda(otu.tab[, ind], meta[ind, ], formula = '~Smoke+Sex+(1|SubjectID)',
feature.dat.type = 'count',
prev.filter = 0.1, is.winsor = TRUE, outlier.pct = 0.03,
p.adj.method = "BH", alpha = 0.1)

**Comment by zhouhj1994** [comment]
Yes, the formula should be '~treatment+geography+age+gender+BMI'. In fact,
LinDA treats no difference between variables and confounders.  You may look
at the list named "output” in the return value storing the result of
differential abundance analysis for each of those fixed effects. Thanks.

**Comment by biofuture** [comment]
HJ, Thanks for the explanation.

**Comment by yan1365** [comment]
Hello,

May I ask except treating all the variables as confounders, it is a way to sperate fixed effect from the random effects. In other words, it is possible to implement the more complex design like two level factorial treatment design, with crossover, something like that.

Thanks

**Comment by zhouhj1994** [comment]
The LinDA treats variables in the same way as the "lmer", so the  categorical variables are treated as 0-1 dummy variables.
(For L-level categorical variable, there are L-1 dummy variables (the remaining one is think of as the reference level), thus we can obtain the effect of each one of the L-1 levels compared to the reference level. The same rule applies to interaction terms (if this is what "crossover" means).  Does this explanation answer your question?
Thanks.
